name: Deploy Server

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "apps/server/**"
      - "packages/shared/**"
      - "./github/workflows/deploy-server.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo git config --global --add safe.directory /opt/fish
            cd /opt/fish
            sudo git pull
            sudo bash ./deploy/deploy.sh
